# Generated by Django 3.0.1 on 2020-02-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
    ]
